/**
 * Custom Service Worker — Push Notification Handler
 *
 * This file is injected into the VitePWA-generated service worker.
 * It listens for push events and shows native notifications on
 * the lock screen and notification bar (like WhatsApp).
 */

import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkOnly, StaleWhileRevalidate, CacheFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { BackgroundSyncPlugin } from 'workbox-background-sync';

// Precache assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

// ── Push Event Handler ──
// This is what shows notifications on the lock screen and notification bar
self.addEventListener('push', (event) => {
  if (!event.data) return;

  let data;
  try {
    data = event.data.json();
  } catch {
    data = {
      title: 'Notification',
      body: event.data.text(),
    };
  }

  const title = data.title || 'THREVOLT';
  const options = {
    body: data.body || '',
    icon: data.icon || '/icons.svg',
    badge: data.badge || '/icons.svg',
    vibrate: [100, 50, 100],
    data: data.data || {},
    tag: data.data?.orderId || data.tag || 'general',
    renotify: true,
    requireInteraction: false,
    actions: data.actions || [],
    // Show on lock screen
    silent: false,
  };

  event.waitUntil(
    self.registration.showNotification(title, options),
  );
});

// ── Notification Click Handler ──
// Opens the relevant page when user taps the notification
self.addEventListener('notificationclick', (event) => {
  event.notification.close();

  const urlToOpen = event.notification.data?.url || '/';
  const orderId = event.notification.data?.orderId;

  // Build the full URL
  let targetUrl = urlToOpen;
  if (orderId && !urlToOpen.includes(orderId)) {
    targetUrl = `/orders/${orderId}`;
  }

  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      // Check if the app is already open
      for (const client of windowClients) {
        if (client.url.includes(self.location.origin) && 'focus' in client) {
          client.focus();
          client.navigate(targetUrl);
          return;
        }
      }
      // Open new window
      if (clients.openWindow) {
        return clients.openWindow(targetUrl);
      }
    }),
  );
});

// ── Notification Close Handler ──
self.addEventListener('notificationclose', (_event) => {
  // Optional: track notification dismissals
});

// ── Background Sync for offline actions ──
const bgSyncPlugin = new BackgroundSyncPlugin('sync-queue', {
  maxRetentionTime: 24 * 60, // 24 hours
});

registerRoute(
  ({ url }) => url.pathname.startsWith('/api/v1/orders'),
  new NetworkOnly({
    plugins: [bgSyncPlugin],
  }),
);

// Cache API responses for offline
registerRoute(
  ({ url, request }) =>
    url.pathname.startsWith('/api/') &&
    request.method === 'GET' &&
    !url.pathname.startsWith('/api/v1/admin/'),
  new StaleWhileRevalidate({
    cacheName: 'api-cache',
    expiration: new ExpirationPlugin({
      maxEntries: 50,
      maxAgeSeconds: 120,
    }),
  }),
);

// Cache images
registerRoute(
  ({ url }) => url.pathname.startsWith('/uploads/'),
  new CacheFirst({
    cacheName: 'image-cache',
    expiration: new ExpirationPlugin({
      maxEntries: 100,
      maxAgeSeconds: 24 * 60 * 60,
    }),
  }),
);
