/**
 * Custom Service Worker — Push Notification Handler
 *
 * This file is injected into the VitePWA-generated service worker.
 * It listens for push events and shows native notifications on
 * the lock screen and notification bar (like WhatsApp).
 */

import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkOnly, StaleWhileRevalidate, CacheFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';

// Precache assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

// ── Immediate Activation ──
// Takes control immediately so pushManager.subscribe has an active worker without closing tabs
self.addEventListener('install', () => {
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim());
});

self.addEventListener('message', (event) => {
  if (event.data === 'SKIP_WAITING' || event.data?.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

// ── Push Event Handler ──
// This is what shows notifications on the lock screen and notification bar
self.addEventListener('push', (event) => {
  let data = {};
  try {
    if (event.data) {
      data = event.data.json();
    }
  } catch {
    try {
      data = {
        title: 'THREVOLT',
        body: event.data ? event.data.text() : 'You have a new update.',
      };
    } catch {
      data = {};
    }
  }

  const title = data.title || 'THREVOLT';
  const targetUrl = data.url || data.data?.url || '/';

  const isChat = data.data?.type === 'chat' || data.data?.type === 'new_chat' || Boolean(data.data?.ticketId);
  const isOrder = Boolean(data.data?.orderId) || data.data?.type === 'order_status' || data.data?.type === 'new_order';

  const options = {
    body: data.body || 'You have a new update.',
    icon: data.icon || '/logo.png',
    badge: data.badge || '/logo.png',
    vibrate: [200, 100, 200, 100, 200],
    data: {
      url: targetUrl,
      ...(data.data || {}),
      timestamp: Date.now(),
    },
    tag: data.data?.orderId
      ? `order-${data.data.orderId}`
      : data.data?.ticketId
      ? `chat-${data.data.ticketId}`
      : 'threvolt-general',
    renotify: true,
    requireInteraction: true,
    actions: isChat
      ? [
          { action: 'reply', title: '💬 View & Reply' },
          { action: 'dismiss', title: 'Dismiss' },
        ]
      : isOrder
      ? [
          { action: 'track', title: '📦 Track Order' },
          { action: 'dismiss', title: 'Dismiss' },
        ]
      : [
          { action: 'open', title: 'View' },
          { action: 'dismiss', title: 'Dismiss' },
        ],
    silent: false,
  };

  event.waitUntil(
    (async () => {
      await self.registration.showNotification(title, options);
      const matchedClients = await clients.matchAll({ type: 'window', includeUncontrolled: true });
      for (const client of matchedClients) {
        client.postMessage({
          type: 'PUSH_NOTIFICATION_RECEIVED',
          payload: { title, body: options.body, url: targetUrl, data: options.data },
        });
      }
    })(),
  );
});

// ── Push Subscription Renewal Handler ──
self.addEventListener('pushsubscriptionchange', (event) => {
  event.waitUntil(
    (async () => {
      try {
        const newSub = await self.registration.pushManager.subscribe(
          event.oldSubscription ? event.oldSubscription.options : { userVisibleOnly: true }
        );
        const windowClients = await clients.matchAll({ type: 'window' });
        for (const client of windowClients) {
          client.postMessage({
            type: 'PUSH_SUBSCRIPTION_CHANGED',
            subscription: newSub.toJSON(),
          });
        }
      } catch (err) {
        console.error('[SW] Failed to renew push subscription:', err);
      }
    })()
  );
});

// ── Notification Click Handler ──
// Opens the relevant page when user taps the notification
self.addEventListener('notificationclick', (event) => {
  event.notification.close();

  if (event.action === 'dismiss') {
    return;
  }

  const rawUrl = event.notification.data?.url || '/';
  const targetUrl = new URL(rawUrl, self.location.origin).href;

  event.waitUntil(
    (async () => {
      const windowClients = await clients.matchAll({ type: 'window', includeUncontrolled: true });
      for (const client of windowClients) {
        if (client.url.startsWith(self.location.origin) && 'focus' in client) {
          if ('navigate' in client) {
            await client.navigate(targetUrl);
          }
          return client.focus();
        }
      }
      if (clients.openWindow) {
        return clients.openWindow(targetUrl);
      }
    })(),
  );
});

// ── Notification Close Handler ──
self.addEventListener('notificationclose', (_event) => {
  // Optional: track notification dismissals
});

// Orders API — Network only (never cache orders offline)
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/v1/orders'),
  new NetworkOnly(),
);

// Cache API responses for offline
registerRoute(
  ({ url, request }) =>
    url.pathname.startsWith('/api/') &&
    request.method === 'GET' &&
    !url.pathname.startsWith('/api/v1/admin/'),
  new StaleWhileRevalidate({
    cacheName: 'api-cache',
    expiration: new ExpirationPlugin({
      maxEntries: 50,
      maxAgeSeconds: 120,
    }),
  }),
);

// Cache images
registerRoute(
  ({ url }) => url.pathname.startsWith('/uploads/'),
  new CacheFirst({
    cacheName: 'image-cache',
    expiration: new ExpirationPlugin({
      maxEntries: 100,
      maxAgeSeconds: 24 * 60 * 60,
    }),
  }),
);
